### ISSUE TITLE
Adding support for custom endpoints

### ISSUE THREAD

**Issue by jamongeon1** [Noelware/s3-action#163]
Hi, would it be possible to add support for custom endpoints? I see that using Wasabi is an integrated feature, but would it be possible to use other S3 compatible endpoints? Specifically, I'd like to use s3.filebase.com as an endpoint.

Thanks!

**Comment by auguwu** [comment]
Thanks for suggesting that, I can add it in the next minor update. :3

**Comment by jamongeon1** [comment]
Awesome, thank you!!

**Comment by auguwu** [comment]
I have added it in a new release of the action! Thanks for the suggestion :3
